version: 2

registries:
  jitpack:
    type: maven-repository
    url: https://jitpack.io
  morphe-github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/morpheapp/registry
    username: x-access-token
    password: ${{secrets.MORPHE_GPR_KEY}}

updates:
  - package-ecosystem: gradle
    directory: /engine
    target-branch: dev
    schedule:
      interval: daily
    registries:
      - jitpack
      - morphe-github-packages
    allow:
      - dependency-name: "app.morphe:morphe-patcher"
      - dependency-name: "app.morphe:morphe-patches-library"
      - dependency-name: "com.github.MorpheApp.smali:smali"
      - dependency-name: "com.github.MorpheApp.smali:smali-baksmali"
    groups:
      morphe-engine:
        patterns:
          - "app.morphe:morphe-patcher"
          - "app.morphe:morphe-patches-library"
          - "com.github.MorpheApp.smali:smali"
          - "com.github.MorpheApp.smali:smali-baksmali"
    commit-message:
      prefix: deps
